apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: transmission
configMapGenerator:
  - name: transmission-scripts
    files:
      - init-killswitch.sh
      - run-wireguard.sh
      - transmission-done-copy.sh
      - proton-port-forward.py
