apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - persistentvolume.yaml
  - persistentvolumeclaim.yaml
  - openclaw-secrets.secret.sops.yaml
  - openclaw-matrix-secrets.secret.sops.yaml
  - configmap.yaml
  - deployment.yaml
  - service.yaml
