apiVersion: v1
data:
    OPENCLAW_GATEWAY_TOKEN: ENC[AES256_GCM,data:W8bbn01pXH92OAxCx3a8bqIHkGGT+ZU+pBrLX5+eX4CbjFmlOd7IDDckFbxo5mAASAYeqObPFnMp5UAHdQOUJdzKKtm22KcwbGmHLkH2Wt+RElbnslC/ew==,iv:6ZBrqSLf5TLrjB3dOoBiPWNWVUSNRpwl89iqj2/90BI=,tag:NcHO/+dMZobjKLQJu+4PSA==,type:str]
    THREE_EIGHT_BASE_URL: ENC[AES256_GCM,data:bRr4AzuLaXYVHxjVXuiRoVWi7zPy7FPTAawHzMzvRXwO+mQ23baDwh42IcuLGmoHTdP0St29sNc=,iv:jCbvIYCAazCnw5gg6fzAIb7WtNZWK8IDu0kRfz7yJYw=,tag:iVNto4Cq959xki+0ePiY2g==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: openclaw-secrets
    namespace: openclaw
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzWEFCMnVjd3d5QkQ4ODds
            dGE2SzNTWWtsQjBYbE50d2RMMWllU2dGMmh3CjhDNmZITlJmM1E4SUlpN2NubWRs
            dnQ4MXZ0czR1b2ZFY0kxU3l2NEQwancKLS0tIEh4WkYrcllRVjBtS3NZWGdLejgz
            aGYvVHdRbmZSNWZUSE44TytEZEtNamcKMlzlMCaW79WyKemxTfy+GWVSlQVLyKHA
            prMMx+oUOI/HlJbwg9hObJEWLEetJnoHZhz+OEs7HLJ23llpIEm4nQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1a73alcfdvadv96hc68nx6sf4wdzysnnnvy4l634hq569vx377chsrck77m
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-22T02:38:29Z"
    mac: ENC[AES256_GCM,data:RKbe9KZYffdWiHFHZG4f+N4SJpkdKvOEa8YRUWhw5IAMf7Zpqo4bx8Eo/x59rhWY5dRPOpteGdnpotVHQ1QWIEbXypC/wpOLVcppJvjqOC1G/2XU7iUeLYgIlrZ4iuOcWtzlIez8E75h8as6gMo6+54CeAv4wIzQzfuR4WtRg1g=,iv:pRPfXp3dkrLWISbIBT6XwI+yw5laIRiRCzcJerj5XtQ=,tag:wYMmCUp5YMoelY8bDLt8aA==,type:str]
    version: 3.13.2
