apiVersion: v1
data:
    OPENCLAW_GATEWAY_TOKEN: ENC[AES256_GCM,data:DWeUh0aEPq78UksFzdYOsrzbiTRd1cinc0g0V+3hO4w5eX0xuh7QbkcKvN3S/Ox8Dtj1q9ZIcVNqrjUR8D6qkv74Sr90ZzdUVg5X07LYQfFX8GwMkHZ9hw==,iv:Zr2n8ewowodZEXCS5lEVWvGsz6YCfXJskQmWhUtoXi8=,tag:Hqb+3hoIR0oTM2TTsMEsSg==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: openclaw-secrets
    namespace: openclaw
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzWEFCMnVjd3d5QkQ4ODds
            dGE2SzNTWWtsQjBYbE50d2RMMWllU2dGMmh3CjhDNmZITlJmM1E4SUlpN2NubWRs
            dnQ4MXZ0czR1b2ZFY0kxU3l2NEQwancKLS0tIEh4WkYrcllRVjBtS3NZWGdLejgz
            aGYvVHdRbmZSNWZUSE44TytEZEtNamcKMlzlMCaW79WyKemxTfy+GWVSlQVLyKHA
            prMMx+oUOI/HlJbwg9hObJEWLEetJnoHZhz+OEs7HLJ23llpIEm4nQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1a73alcfdvadv96hc68nx6sf4wdzysnnnvy4l634hq569vx377chsrck77m
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-18T21:50:24Z"
    mac: ENC[AES256_GCM,data:q1JsJLGsomnhWv1wm/tFjLUQs07SZmvD5MUp4wL2exVO4LKmuNrEfDsIv31pg9jUi/7mYNC+28NX3hc2rJ2xp01hTSYBNkp5UluftFF9OkBeCqK+H7wEQ5G6Y5bGkHhZl+6HtyskHIrlShNVg7ehaLkRPeoWoYP0Dyr+q8oOJ2U=,iv:ToRrRK7m5uzge8bNn6pClK4IUGrOvn3hqzEegViSrfE=,tag:4MS1ss2Ve0t9M6cN5pp2Rw==,type:str]
    version: 3.13.2
