apiVersion: v1
data:
    OPENCLAW_GATEWAY_TOKEN: ENC[AES256_GCM,data:W8bbn01pXH92OAxCx3a8bqIHkGGT+ZU+pBrLX5+eX4CbjFmlOd7IDDckFbxo5mAASAYeqObPFnMp5UAHdQOUJdzKKtm22KcwbGmHLkH2Wt+RElbnslC/ew==,iv:6ZBrqSLf5TLrjB3dOoBiPWNWVUSNRpwl89iqj2/90BI=,tag:NcHO/+dMZobjKLQJu+4PSA==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: openclaw-secrets
    namespace: openclaw
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzWEFCMnVjd3d5QkQ4ODds
            dGE2SzNTWWtsQjBYbE50d2RMMWllU2dGMmh3CjhDNmZITlJmM1E4SUlpN2NubWRs
            dnQ4MXZ0czR1b2ZFY0kxU3l2NEQwancKLS0tIEh4WkYrcllRVjBtS3NZWGdLejgz
            aGYvVHdRbmZSNWZUSE44TytEZEtNamcKMlzlMCaW79WyKemxTfy+GWVSlQVLyKHA
            prMMx+oUOI/HlJbwg9hObJEWLEetJnoHZhz+OEs7HLJ23llpIEm4nQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1a73alcfdvadv96hc68nx6sf4wdzysnnnvy4l634hq569vx377chsrck77m
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-15T06:00:59Z"
    mac: ENC[AES256_GCM,data:igi1z0uZyH2JpLEVtmDwIBnSbRyNDBI6kOu3gfe4P/nLEqsbKGxnZDuzICSUbXR/wYVYqxEuqkQtOHeRELguLqJzZIRxGpteXuiFCZgQJvkGH0BLH2XuF7b6q/MQLfxhJPtM40ajSfAcFRmmq4qoPuMbxayMXMpLRhbD4ZMIjAs=,iv:7qMFKrK2N+GiMgKb57kS3/wEG1Y98oTtZDqbcExs8IU=,tag:BoZkoRqK5K01ug0Ezq7z/g==,type:str]
    version: 3.13.2
