apiVersion: v1
kind: Secret
metadata:
    name: openclaw-matrix-secrets
    namespace: openclaw
stringData:
    MATRIX_ACCESS_TOKEN: ENC[AES256_GCM,data:Y5sVee5opOZrhQTcqyy6qDQDKSAsl3TC3dNe18RWWGFl5WIorgi8,iv:FB9h+5i3iiijypGk/YTqSh68agauWs7vK7Wle0xNI8E=,tag:EkhQGRT8lPx7bfgsY+w6Vg==,type:str]
    MATRIX_GROK_NUMBER1_ACCESS_TOKEN: ENC[AES256_GCM,data:m21IW8dLo+1iMMsY4PEAuNS6FlHxTORQkmHvXLMXfzAFFe2nDnkzhuHDDlx5DwOF,iv:SjfdMA0VhRyXaObYftPCViUqZ4OkhxNBWdBgyPIudLo=,tag:1goPuj+nXkP3RFQyNXmgAQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUaXphOUdzY0loZlpyNHJJ
            cldOSEZ2S3A4VmplT05hQ1l3cndsdDVxNXhFCmtabzV6dGc3MHNXNmtqSUN4RW8x
            MVZTbDNPZFd5dFhDSWtWRVV2V0lUKzgKLS0tIGVaamxJeUdGcWdKUkwxdlJoTEVP
            OCtKMVV3a1QxenMwcUd1RzNGZFF5eWMKFG+pm1TzKaLCnapGy/9BnAQ6o9xufS57
            VoNAs4R8otIhQR+zu0mjRLn5cSgeehbFJjtlhAa/VjBuAvZ6lNbZXQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1a73alcfdvadv96hc68nx6sf4wdzysnnnvy4l634hq569vx377chsrck77m
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-15T06:00:49Z"
    mac: ENC[AES256_GCM,data:OO0h5PiEQtgwn67DVynC6+edSmtiSTzMwe3XyBOz3LOYfqO2viNJhM20KjrUYnfIhzHBSrQhuzEGQSeJWwcnVSl1gSXvjU4a1BCENCQX7ABrLYPO0z2nhqSzKBHkR7oHgdxogLsoEiwcdaLTt1GIv3QSsU8JeAUYeUAanz0wh2o=,iv:YoVZ93y3dSkRpIaCMAzCeVfRLv2UHHz7lzLLHkO8KZM=,tag:8PzB6SW01uPmLAbBT7IpdQ==,type:str]
    version: 3.10.2
