apiVersion: v1
kind: Secret
metadata:
    name: openclaw-matrix-secrets
    namespace: openclaw
stringData:
    MATRIX_ACCESS_TOKEN: ENC[AES256_GCM,data:Y5sVee5opOZrhQTcqyy6qDQDKSAsl3TC3dNe18RWWGFl5WIorgi8,iv:FB9h+5i3iiijypGk/YTqSh68agauWs7vK7Wle0xNI8E=,tag:EkhQGRT8lPx7bfgsY+w6Vg==,type:str]
    MATRIX_GROK_NUMBER1_ACCESS_TOKEN: ENC[AES256_GCM,data:m21IW8dLo+1iMMsY4PEAuNS6FlHxTORQkmHvXLMXfzAFFe2nDnkzhuHDDlx5DwOF,iv:SjfdMA0VhRyXaObYftPCViUqZ4OkhxNBWdBgyPIudLo=,tag:1goPuj+nXkP3RFQyNXmgAQ==,type:str]
    MATRIX_PERSONAL_ACCESS_TOKEN: ENC[AES256_GCM,data:egejHSe7OUQdzxVpvVRHNdwKIsIffEZzZ/xwfaITcx6ZU/cYoJ4u2fJ79A==,iv:SYcGq1OebCpCF0vCQFm9c8uAK+Z5V6SmtBN0+utlewc=,tag:dt5YDGfV6B9OXxLMRwiU1Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUaXphOUdzY0loZlpyNHJJ
            cldOSEZ2S3A4VmplT05hQ1l3cndsdDVxNXhFCmtabzV6dGc3MHNXNmtqSUN4RW8x
            MVZTbDNPZFd5dFhDSWtWRVV2V0lUKzgKLS0tIGVaamxJeUdGcWdKUkwxdlJoTEVP
            OCtKMVV3a1QxenMwcUd1RzNGZFF5eWMKFG+pm1TzKaLCnapGy/9BnAQ6o9xufS57
            VoNAs4R8otIhQR+zu0mjRLn5cSgeehbFJjtlhAa/VjBuAvZ6lNbZXQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1a73alcfdvadv96hc68nx6sf4wdzysnnnvy4l634hq569vx377chsrck77m
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-17T01:22:47Z"
    mac: ENC[AES256_GCM,data:d1d9PrI+w0VMIbs4y3C6I08zxE2kRWvq3+yr8G9mR2mK9kgWzbkv5UNuJw9s1BVzYffT91uVv+WuDeEB2SK59cLGBz6awd8QFBkqaTxQtYBagmEf9Gigl9BGlH7zKoT+cRaYHzcGeW0dmQNedFfXT5ZWEitTQFKL7BMBxBtAbYU=,iv:5t3HDaIIcJrZGmALOBUl38PBt88KoALYtG9WmnbXBZw=,tag:KvsWnFcKGVPC+YoKJBAoxw==,type:str]
    version: 3.10.2
