apiVersion: v1
kind: Secret
metadata:
    name: openclaw-matrix-secrets
    namespace: openclaw
stringData:
    MATRIX_ACCESS_TOKEN: ENC[AES256_GCM,data:Y5sVee5opOZrhQTcqyy6qDQDKSAsl3TC3dNe18RWWGFl5WIorgi8,iv:FB9h+5i3iiijypGk/YTqSh68agauWs7vK7Wle0xNI8E=,tag:EkhQGRT8lPx7bfgsY+w6Vg==,type:str]
sops:
    age:
        - recipient: age1a73alcfdvadv96hc68nx6sf4wdzysnnnvy4l634hq569vx377chsrck77m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUaXphOUdzY0loZlpyNHJJ
            cldOSEZ2S3A4VmplT05hQ1l3cndsdDVxNXhFCmtabzV6dGc3MHNXNmtqSUN4RW8x
            MVZTbDNPZFd5dFhDSWtWRVV2V0lUKzgKLS0tIGVaamxJeUdGcWdKUkwxdlJoTEVP
            OCtKMVV3a1QxenMwcUd1RzNGZFF5eWMKFG+pm1TzKaLCnapGy/9BnAQ6o9xufS57
            VoNAs4R8otIhQR+zu0mjRLn5cSgeehbFJjtlhAa/VjBuAvZ6lNbZXQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-15T00:04:39Z"
    mac: ENC[AES256_GCM,data:eO0aL36nWwBLkgJPAlKGHChYElWK/dvDnsAJbWdxFCsnFBYMHmYv7T0uWpftRcRQKpAQUUWnNIqAktNdObEIplHrcmQdRbHxp0hHAAFZlGT2xLi5nUVJUCB0GVpNMMVLsuQ2SzSnXWn94vthpeGQ9x1HAx1dGiPW43LFW0+FnOE=,iv:whogAMjKgo4T5d6dLPbZFqSqoiuThvoGU/Z+emRFVZs=,tag:+1pM6hUIcYfx/D04ft8whg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
