apiVersion: apps/v1
kind: Deployment
metadata:
  name: monero-node
  namespace: monero
spec:
  replicas: 0
  selector:
    matchLabels:
      app: monero-node
  template:
    metadata:
      labels:
        app: monero-node
    spec:
      containers:
        - name: monero
          image: ghcr.io/sethforprivacy/simple-monerod:latest
          args:
            - "--p2p-bind-ip=0.0.0.0"
            - "--p2p-bind-port=18080"
            - "--prune-blockchain"
            - "--data-dir=/home/monero/.bitmonero"
          ports:
            - containerPort: 18080
              name: p2p
          volumeMounts:
            - name: blockchain-data
              mountPath: /home/monero/.bitmonero
      volumes:
        - name: blockchain-data
          hostPath:
            path: /mnt/erithc-clusterfiles/k3s-volumes/monero
            type: Directory
