apiVersion: v1
kind: PersistentVolume
metadata:
  name: monero-data
spec:
  capacity:
    storage: 150Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  hostPath:
    path: /mnt/twindrives-clusterfiles/monero
    type: DirectoryOrCreate
  claimRef:
    namespace: monero
    name: monero-data
