apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: monero-data
  namespace: monero
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 150Gi
  storageClassName: ""
  volumeName: monero-data
