apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: monero-blockchain-pvc
  namespace: monero
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 100Gi
  volumeName: monero-blockchain-pv
