apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - persistentvolume.yaml
  - persistentvolumeclaim.yaml
  - synapse-db.secret.sops.yaml
  - synapse-secrets.secret.sops.yaml
  - deployment.yaml
  - service.yaml
  - element-web-configmap.yaml
  - element-web-deployment.yaml
  - element-web-service.yaml
