apiVersion: v1
kind: PersistentVolume
metadata:
  name: matrix-synapse-data
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  hostPath:
    path: /mnt/userdata-clusterfiles/k3s-volumes/matrix-synapse
    type: DirectoryOrCreate
  claimRef:
    namespace: matrix
    name: matrix-synapse-data
