apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: matrix-synapse-data
  namespace: matrix
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: ""
  volumeName: matrix-synapse-data
