apiVersion: v1
data:
    POSTGRES_DB: ENC[AES256_GCM,data:gqI0IFfxi+RiE2Io,iv:NwzRttjhKZh7/xCeUWODKahU0Udf3V8OiX1oI8l60Gs=,tag:H+eqNa0QzqdUeGk8Fyy6Xw==,type:str]
    POSTGRES_HOST: ENC[AES256_GCM,data:o3E51BHA+liqLix0FvL0HlCJ4tfhK14yg8cmrEF9dqBa5+nfsTDIezJc0DhzbyKc,iv:RoZLjE1fKgzQS2K5Hn5SZ3xTs0Bh0B+By2Ngp6r1qGk=,tag:hytrvNig2c5sm0b4AWTvcg==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:xCfEDNPAhZHBPZMrMynZleQVL4HSmzSCOWsLhFY1FNuss42c8WdCsHwkXqVW36SmroANkdNfg8PgkAjIzoxT3Q==,iv:yADqmIXfAahQXj8/+l0q7II1RFnF6HLg2jFKsxndaNc=,tag:5LVCPhvlv2CbnOooDvNDzQ==,type:str]
    POSTGRES_PORT: ENC[AES256_GCM,data:KnlONMMf6+Y=,iv:4hxRmhQh1HkRpedgO5UTOXROS6FkNSNPGxBezYVm+w0=,tag:V5FIQYiogO+R+E6PK9xlyQ==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:ATRV+WSOTFhzDC83,iv:URhEDOydBdHKDjYgfC4t38Oz/6WHdIp/xXcCGg5qWIg=,tag:7Ovtzd7MxzvHTbK4EL51MQ==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: synapse-db
    namespace: matrix
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJOGpYWUZJN2MrSUFRbWdw
            OTBYcDdEdk5PK25DYmx0L0R2SUNZZ0pySTFnCjYzOUZndXMwbGx2Z0lrY0FpdmZp
            ZHhveDU5TFdDMkxYaVdCU0ltS3JpSjQKLS0tIFpiZ3ZobFBBTU01SmFTMExnZkNS
            Tyt2ekZmSnBrZVBIRnp4TEpNWnBQeTAKM/xm69MtEwCCATQD8nd4QVzNF1PmBCBl
            kYksh4TAqRUOcv50Kac2yDCND3q8EVd+QAXBWTibELpmChxHvxPP2g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1a73alcfdvadv96hc68nx6sf4wdzysnnnvy4l634hq569vx377chsrck77m
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-14T18:21:48Z"
    mac: ENC[AES256_GCM,data:mf9tBSuSMFygRP/9wjVbIYaObke4bzjKkpI/S1J2bzQt/aXVtvAN550nPZxgKmsBMILmaJCYbq42ET7dEVSjEeSZaZupOFE0rSCP61x+msWYCjqOYGlYecYys8QTkJALdEp6hExtW3UszZAyDnrXFxxJekM0FtU+ojG+6+ZXErY=,iv:Z27Iq+xujw4IcJivWEkG2TFdCUI2/uDoMbt1kApl/YU=,tag:ZDThb03pTInTdHr9cxcbQA==,type:str]
    version: 3.13.2
