apiVersion: v1
data:
    FORM_SECRET: ENC[AES256_GCM,data:sRGwt2oRF8DHTtTbxrcOnk9tAQLq/cbVWf/9IIpH2r40wJDe57IYnjg8gFkUS9Tm8i2gx+ZAqUdVJZrUds+pndPM+kI3cGSzd/vsY90cJE0rdObXTOUTptp+T6d0AFOSVxb3kgq3HERF6k/JKPTZ2KwGYrqUGc5qULvfo1V8q3ETDfCu8KlkLTN7ZStA8hy8yTTBVoKaeQf0K5aliDu+DY07SES31IQXBXVLeg==,iv:a+WkV/9Mj+wyPpbeNg1G06Mo5c5Cs+cn/CCWLO+0JAA=,tag:okGQ0xOpvw+NpEmFtaHuBg==,type:str]
    MACAROON_SECRET_KEY: ENC[AES256_GCM,data:6OBFJYZXfYTLFDbk6uc+oIPmiYMT+NmVL9QFiCDdmS1thF5sTDoQOCqCPJG4qEAzeF6MPtjqXBncXfd45pMboymLG5zioTJwk3D61I7qfVTIruyW2v3OUNoEU9gggQY9ToDb/GgA43yuPu+ADzsSgJNdQXht8XQvvEWMOHiAkhLDr4JzkCZuE2YVdCOjKuvWKu3dteB/UEpsaD9to7i2J6W5R7RLkoFf8lIQJA==,iv:/x0GyVhdISZps5mMF5HWNC3qFXMusdA4LalHMQimF/c=,tag:o4PRYTpvuPw4r7a/hh39EQ==,type:str]
    REGISTRATION_SHARED_SECRET: ENC[AES256_GCM,data:8R0jjjzeTE+GHV7NDiJN2YCgDFDfbs5HKszWDkzcmUVWDcsfhjbOxTNvHXKkUkXujTMlWe2sfqD8In7eEJkonKTNoCwPuvgja2dI/ucWjQdQko9TIoPRR2RFi4NgR7vpfbk0xpQK+GdoibUA18UrZW0b68R0Eglcp31208VAFjLyFgPY57/l1lwaZ0b2uvCnBhACl1QooQBs0hqEYJxRDwpU63k3887xA1VuqQ==,iv:N3z3LUDcGzEnsvNU8mpwiZvaqNkXMENzTmWNbOTq3L8=,tag:5C9PWeXffYtEAwLCotYhcA==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: synapse-secrets
    namespace: matrix
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaZ3pHaERiV0EzMnMvc24x
            SWhndkhTbXZzV1RYUzVwc0tLTGZZUmF3Z2pZCkFrVk1WRnNDYVRnUzF3VFhpT3JP
            RS9oOTB4MUoxeTg0WWN5K3o4cVZxZlkKLS0tIFl6Rlkwa1JtZzRjdUR4dWpablR3
            MnA5SFMyMEErNGZxV0dmMExBK3VqZVkKoOpg/CVi7tJGczqjFtA50OHO+VVbUCoh
            8xj/ADzWCiKsHZwg+mua6dyNV5R0TfkSYedZYBCQjx/FZTdoaPlJgw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1a73alcfdvadv96hc68nx6sf4wdzysnnnvy4l634hq569vx377chsrck77m
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-14T18:27:19Z"
    mac: ENC[AES256_GCM,data:00+1xAEZOoh+Fpue1ulaacaVFydHIK9gi0tbTWkHx5deFV0uBeeHZSMyCSrybF43xIwSyFnUSVbpJmgQ+miN6sR0bqC1sYsVfZPsTmGnc7FqKvbfz6ub6wXVmhNSSP8DN9deIIA8sgDLhcBVt1GiFf1hsUauSPucI4sHHI9VZAM=,iv:8FLaIW7o3AMSdmSl4HqWTKNKLK3jXd56qgfsaSYZmpc=,tag:q0zJ/TAvgeBJ0FfD7BAb2A==,type:str]
    version: 3.13.2
