apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - persistentvolume.yaml
  - persistentvolumeclaim.yaml
  - persistentvolume-incoming.yaml
  - persistentvolumeclaim-incoming.yaml
  - scripts
  - proton-wireguard.secret.sops.yaml
  - deployment.yaml
