apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: transmission-incoming
  namespace: transmission
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: ""
  volumeName: transmission-incoming
