apiVersion: v1
kind: PersistentVolume
metadata:
  name: transmission-data
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  hostPath:
    path: /mnt/twindrives-clusterfiles/k3s-volumes/transmission
    type: DirectoryOrCreate
  claimRef:
    namespace: transmission
    name: transmission-data
