apiVersion: v1
data:
    wg0.conf: ENC[AES256_GCM,data:+U4g5kXLGECruk0s3snMDbaU+fkWhi6wasoduhZfeU3DRag00vRkH7Xvd9KR0ozK7pNXzCkOSTvXl6rCTwmPZ3Ch/NkHFZHAPTDIfN5S4EEh7o5TIuRWLELWxXDvsiIUk4Fdo0sbJb6yYsPS+WE7VrW7jZzIMnyA9uk4ylmlYt1ZLTQm/IFO08LKAtg0DZGUAeL+OgcJO57ulXr/aILep5353N2e7gCxNzBEYlkvNaxrlrl8V7VJR9WfGvSOQMXRmMRgzt8sdBPWBUUsBI2rUOj67d1znAjG8BQ2XywIKAa4BFaFdlPACQNv/qi5VnZRzgXrEeUU63uqpmn6UHnGBiUSpLbqKQCU+889DC9ST1FxL2cYKK0tssNtuCt1ngDeqCOJpniGSlImHfgat3ihH2IjgBVQ3EMyIV3+SWgRCGLSVc1dS2LpRGw2zu2dwYvUFyervTOdeiY6gmoRXgF4iy1uQRudxQq9DDGckrcPYgyhrm6exr8KgqAtKcSaf60QeLIRwdp7NhPra8CkHlXHTYaGmW98Q5xP90rz0M6Dv5JAZ0hSSpCNg0D5hydqb3vR6QuFqyKSBf3l+HYOmfL8HZpCOjPsobHlIjf1aGuMCYQCJInjjXbhW5N2s2N8G40uQ7fipVpcNfTO6wDGmxUj2thCxX/rutKGzoWbfe1rWUtQwtoX4QvoO1RLAR1PgBbrJNJIec92nWY4vgp2xLL6sWDSMCgFTwOG80qKfQNJc5NdivFGD39EmxFD85h3ORuUQ5YpE0D7m2c68gRzNLXsmazPWFpicWfXszqnOlfCyH2bODwOyFvhoud05O2M+YwBF/GhM817g1cU8yIliblgvD608fYcHLxzhwmIYhn/9rLVWtLkImybwwnj91BjdIlL81uwoZG5ZvJSZqI7r+ye3lptAbZLR+KvmwXDWsg0GTt4Vn/PYkrYwLk95ZtV5xZLZs3zJtNkexM=,iv:aNz6CdDUGKU79a6KGgCcahdB+6BvxSpJbWIJBghwDyA=,tag:3zk8caTy97qzHMisLvOHbg==,type:str]
kind: Secret
metadata:
    name: transmission-proton-wireguard
    namespace: transmission
sops:
    age:
        - recipient: age1a73alcfdvadv96hc68nx6sf4wdzysnnnvy4l634hq569vx377chsrck77m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuN3FQelhjMEd1aDlvRmlN
            VzdjRC9DNkVueWpFZitiR1dlOVZ1UFFSSVdvCjJUN2MvOE1DVGkyQjdZb3JFY1BX
            VG0yVHJNKzAvY2tNNzEzQjFZRkxUaUkKLS0tIFBVS0p3Q1h5MjE1OGkrVmxzaTFx
            b3p4Lzk2cWcxSDJkWEM0cElLalRKemsKnvXFJPjbFUfM13m+ra5o16Q/zkAKZLAa
            /CY+VaO2IUqOryJgo9P6UxGI2kK7Xyc5/CePRt6cUD67cQAU9CCiVQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-16T01:47:38Z"
    mac: ENC[AES256_GCM,data:DAAsbUmcHpVBK3anFoQPTPZi/Sbwbvtb3Hruvf9rKQuFdpdr9cuvF2BLguIbrnc+7Wr7/Nrld0b31+t4PVtrCc1wJHD6HOp6G0CE9SNrEvRCmMiI5ic22qMNljM6mKn8hPGv12VUtCDipq1Fzlczg/jKomBIYKDWXXO+l40vJco=,iv:Y0At5c3UXW9c98b5Kd9oLN4NfyrNJp+qhuviIbjDDPI=,tag:CLF6HNxI8MM/ga3wnZy7dw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
