apiVersion: v1
kind: PersistentVolume
metadata:
  name: syncthing-data
spec:
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  hostPath:
    path: /mnt/workfiles/synced
    type: DirectoryOrCreate
  claimRef:
    namespace: syncthing
    name: syncthing-data
