apiVersion: v1
data:
    identity: ENC[AES256_GCM,data:KalFQ0b/wCcJKD+RE69oPEDkJlgEB2/AbvC06+J1CqQ5mbECmGQqZzS4yQAp08Fo0yNBAZsMPb2KrvLgJmbNVCdLf/04K9JZohCRt+4SYc8SZPoMuPLPgo7uGeMMJ29atTnO5X4GmHUoa2Jj3HVFJhc70RtPtk9RO6/pApj2vFLUm45ptilJBTGqdG3opoUs+D6D9CmgItN6B2yFmE5e0Wa49qyEmgqVRbyhZ3KsRl+bFgRd7wRyPzNomI4aA12xhG8vAjK1EpdDs8xmnA1XgAc7XUb7PHoa83n/MUDVeqm5I0IQ9tXr+10mTiH27cTjljxJCpGWEgFaki6KusWPajA56yARfGg8WwECMutt3cEToNAWylzugZ8aXZvkv0RaBkIWyM5/yj+W6MOy/IksCKNADoe1mvrIZuUcygaO0528+AYcn1ddo3ne1EFT2e3dNUKnJddfn4WUsQP5S54V8dFlsis9MohISuRKjGHQR58Z/mRsz0g5PQldgU4BrLfey//dt8uAHnRgdaHkCKCdxE/d6kHvSQDRDs0R5k/eQRRjiu6fb50CFwz2K5B03TpovqoOSWjVGCsaBy4vwzmOM89Su0SFM7VeD4a2V5dRePmjck3Qo19DxXKjZve4AccnjxL3yE83IkkfsnXTvxTrvzPqH9+d5vfXmeOqLfzms7v68YSrv59SfY+J4suCW0GhzmGtOAZRYDG34sb9fi7ebdz61PjHe65uPiGbHjsN2T/AKuTr48W/vjyiLDbMbhXk,iv:YhETbLIrtaG5gpqdj1UvQug+z8eS1r5O2atEKRvzeIg=,tag:fjP981W58tyCqa2p2cOTpA==,type:str]
    identity.pub: ENC[AES256_GCM,data:8H8+/HQdbfi+8OfkMJjl+rbCCKr225bsqsVgLqvhICie2ozz1zRShQ4hCxvO6O4GUbcgq+kMzvcRQ9HbQNfrM+xG0MVrCzF+jPSrCdO0iwnQ+adX6XNrEfK/s/uetLIR04Y++a7dmdkftayB0w7aVPQPl3t5AW79DYkefqAkwySNWk0gUi3NJ59R1pVmzxk0opAyCGTCckt6SFCn,iv:RS7w1dDr7MlZCDsAn7Nx9gsDGj4JXOtL7jNcei8liog=,tag:XhTZhPtjwFiALmDJdkqtig==,type:str]
    known_hosts: ENC[AES256_GCM,data:rOt5q862qNqOyDIS+/sbhy1n4SJuzeAox5y8gpTGwznLRlEkLvROrAlLKAK6yiBq9ER8ERRSfVNCfH0ocRl8FTArgmIANlhdfuVXoJHuuRCDCRJ4mC87hkO/T+JhOUFQXtxhQPLfuWL4D11XYyXY3Wj9vWygGv7wUDNJd2Ysh1Jo7WPDXyrrqPp8KuWOw/TtPgU15Rx1xJ0iWVDrD+Q5O+gZI4C9xH64+opE4FtaNcRikK0jDuMWNHARTmydKJ5dR3y8eYgSLz1TXh+GQrQCtUDzZbXgE2hmIWMZdBWsrrA9lP66,iv:2GTAFLsQDbZSpUn8SzRMrpfI5/gpSFtwMBcUCpkE0fk=,tag:ESIMpYmrZ+aNDmcr2+Pnlg==,type:str]
kind: Secret
metadata:
    name: openclaw-agents-git-auth
    namespace: flux-system
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuT1B3d1pxa1pTb2VLSWcw
            aWtWTzR3dFI5NWtXNkE4aUtpNENITE05SVVvCktDWVBoR1g4blpxaHFCS2lXZ1Uw
            UkhZUDlzOTVDTENKS01wOSt6NmJ6U0UKLS0tIEVIQkk3anJqU1dOYlk3ZnFCaEpt
            cHdmQXZ5T3MyVkx3RjhES0JIdERpWEkKUOdI2hm7pu1MNh0T15TaamQpShBuLdUt
            8DAHyMq0DC0pk2JxNSvCahxlINwu9nDIeyhS47NYP78GL1hSd5krpQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1a73alcfdvadv96hc68nx6sf4wdzysnnnvy4l634hq569vx377chsrck77m
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-16T00:13:16Z"
    mac: ENC[AES256_GCM,data:ROPeE7168ze+sIe5kyli9/wKhPB/zOqUlINTpaan2UzwQZgzX3UhPNtvkC6iaRNLf4wTsYf45Z/3xmx6dvZaA70RWJNWuyOBn4ISgGyXkiZPannNsoGnQBpLmJounaF+nLYH9aQTCN7Pcr0eq+/iN8FI2lsspucio8QU8YwxNcY=,iv:IwBpNhKzApIrjb30P4iCbcxj6gyFE6SPSyL9M2H9CP4=,tag:3412qnZA/N+TjGsLXyPWkw==,type:str]
    version: 3.13.3

