apiVersion: v1
data:
    database: ENC[AES256_GCM,data:I/kabc8WCLY=,iv:hDzzkI51vF/ph0WYZOZjMm3x4nnmcbG1XuRWOlLqxNg=,tag:xMbpDMaxKI8c2YADNWCAVg==,type:str]
    database-type: ENC[AES256_GCM,data:hLs+WWND3YKSJZ0e+9CJdQ==,iv:3ISoVLlXlASd45FF0jsxCHv0TVxAEiDc6G7Sx1EqaJo=,tag:G+p+18ksrFmLfZB+G/zzJQ==,type:str]
    host: ENC[AES256_GCM,data:2ktAfJZTnm4l8z01E+aaKeA3uKhsjT+2iNLjKBoHp1bjEZ0rDlt6q0dvl96feESv,iv:eVYmycqBzpCGw3D5NpW+MQAbEl6sh/fMeODHJCgWyxQ=,tag:Slh+ZBzHi0d0M9kOaJaaGQ==,type:str]
    password: ENC[AES256_GCM,data:8EjFmYEqsG6nNWjb7vm+HiNhHJQBJouNtPfNpR2M6Sz8u7uNnBiA4xMmXeA=,iv:Pc2Foz2z46E0IMQjagmALN0ZR1bMIHKgk+PVd/Z+ltY=,tag:7i8ZXK3hV00zxLlllwptQw==,type:str]
    port: ENC[AES256_GCM,data:z/DkhlWNLfw=,iv:hTrfGxoJcsh4whCM41Bm4m+T4D2LDxxWcTM4aVHRI0A=,tag:SC6M+yB0elxA7DiMer72gw==,type:str]
    username: ENC[AES256_GCM,data:tVVbLMK1xg0=,iv:E2BWelQhaYvPqeZnED/8wTAMIPFL2LGyTJh00ezUFWk=,tag:tRTg080zNy2rHI1L9VSBVw==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: chat-db
    namespace: chat
sops:
    age:
        - recipient: age1a73alcfdvadv96hc68nx6sf4wdzysnnnvy4l634hq569vx377chsrck77m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoRXlhdUs4ZmNGOEF6cVRD
            TEI2YXdOWE16K0VuWS84NnRPSkEwdVR1YTBBClNFWG8vUkpMWTAwRDNoMEJlTjN3
            OHAwZUdBRjcwSDVFTng2MFgrdmpVeE0KLS0tIFBBZERDT2kzcnFBdENLQloxNG1L
            ZVRSeUJ5cjBGZW04ZW5WTVIxb3VnaTAKorWtEoaDPom5P2XgclYJ9Pku1MgHTOW1
            04qu1qvnUqFtzjz07iBO/LxyFYQhOwZFaCbDXdXB/Xvacz6TbgTpmQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-17T02:49:07Z"
    mac: ENC[AES256_GCM,data:HMw3VCz9LwgHGEq6yXju0bfE2H6lPApeq45TkAqLwfY0aPRkUuEIX90umP/rnuSH8xzXCZVr7y3EzYbbZMNIiTNh+dyxAcjUVLzsIGizKC+w/aJrk6kUU5OovBpILBUhwA4MZoFXV47G32YX+8W8y+ZIQU3W53bv2gU1Ngzx1eo=,iv:nAtaZJNS9enkfSzTZutscezLRR1d+//8MjzZG1OEaLg=,tag:MzbsZ5wSiIkhyT+F8a/YcQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
