apiVersion: v1
data:
    secret-key: ENC[AES256_GCM,data:7YpPj3BImqfUAsTKhy2HHpy+BcXKOvWrKddXAPEh8T2xX9bMc8A+uzrrDwaUv6TJTKlyxeQ2ldhx5YTYIRmhD+ubiljzkUECzL+Vcg5SiqNgleahvZ/JZA==,iv:fmAqWDS9RCm+nH5zBPrcXtSOX7dtOh27274dcAr+EVw=,tag:LIgheuDF1wMUdD2Tn78bqw==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: chat-webui
    namespace: chat
sops:
    age:
        - recipient: age1a73alcfdvadv96hc68nx6sf4wdzysnnnvy4l634hq569vx377chsrck77m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFTnM1eHdKVzVXRlI3bVJC
            KzZ0RnMvYXNFR29zaXNTc0sxd2lpbGNaYUE4CkRDUGU4dTQ2R1p5T1o5b0tjOTd5
            b3RxVkd6b1BUczJWVHRDaEQxWW9uSjgKLS0tIDdVR2Zzang5dmlWVHlTTjk4czIv
            SDJlMW1RNGhHb2lOYjhRNndiVUFjeE0KsqGiOaZrCTVMUUlU/YYGzgzBPwkLL4q7
            2ya3fnVfGj1Eiszheq8Ngy68KIbyjoa3a7Ulbp5GUxwkHgYO3GLn+Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-17T02:41:09Z"
    mac: ENC[AES256_GCM,data:59lzZw9vbsATVkNoL+YB6Mvc9bbrGWj8Pno0kOZbQSBvoQOr1Hz+W7mV3lEDa2zTTpmEnjMynIX7zMnRdgYQ+/ICZGlGTnThahin96zTkYtFR7TvsP0CJcB8n0as+sa+cfV1db//B4g+4epgM4DxPOsQucvSxti6Wxv0nCeuFVU=,iv:u7T6Vq0Is2JDe0hEgG/AR0lkMRt7CA+bzJgr/T+mz5k=,tag:EGiX9E4OYNUn2E8hLEy8kA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
