apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitlab-garage-meta-0
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  hostPath:
    path: /mnt/userdata-clusterfiles/k3s-volumes/gitlab-garage/meta-0
    type: DirectoryOrCreate
  claimRef:
    namespace: gitlab
    name: meta-gitlab-garage-0
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitlab-garage-meta-1
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  hostPath:
    path: /mnt/userdata-clusterfiles/k3s-volumes/gitlab-garage/meta-1
    type: DirectoryOrCreate
  claimRef:
    namespace: gitlab
    name: meta-gitlab-garage-1
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitlab-garage-meta-2
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  hostPath:
    path: /mnt/userdata-clusterfiles/k3s-volumes/gitlab-garage/meta-2
    type: DirectoryOrCreate
  claimRef:
    namespace: gitlab
    name: meta-gitlab-garage-2
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitlab-garage-data-0
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  hostPath:
    path: /mnt/userdata-clusterfiles/k3s-volumes/gitlab-garage/data-0
    type: DirectoryOrCreate
  claimRef:
    namespace: gitlab
    name: data-gitlab-garage-0
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitlab-garage-data-1
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  hostPath:
    path: /mnt/userdata-clusterfiles/k3s-volumes/gitlab-garage/data-1
    type: DirectoryOrCreate
  claimRef:
    namespace: gitlab
    name: data-gitlab-garage-1
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitlab-garage-data-2
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  hostPath:
    path: /mnt/userdata-clusterfiles/k3s-volumes/gitlab-garage/data-2
    type: DirectoryOrCreate
  claimRef:
    namespace: gitlab
    name: data-gitlab-garage-2
