apiVersion: v1
kind: Secret
metadata:
    name: gitlab-garage
    namespace: gitlab
stringData:
    accessKey: ENC[AES256_GCM,data:9PV43NGPCJYES3INRx9wGoESfFrsE+qNyr8=,iv:K1Jc4SbS5TgW1MSBJ9VfqVNArmuW2JUx03XviK64GQA=,tag:KrQdWIMyd9/YHuvO+JkIaA==,type:str]
    secretKey: ENC[AES256_GCM,data:2OibWrTREuv1J5to7R75vxer2mluXYzFbibt+H8gsh97IF5jv4ouYaTrg9GDMNo4oXXzgytGK5YHUacWrHQitw==,iv:PPSYlLElMz3ByjwHhp+UziL5HSVmJ0t4yWAEebs6KKs=,tag:XEnndYlf6cmrYGxIn/hSFA==,type:str]
    connection: ENC[AES256_GCM,data:Tvzc7Kl/8QL3g9qcIlqqU9OzRcW2dwo7QYZmmGRmBblopW3Sr5y8NEZ+E3/XpzW2awKNaeB6KC5mh+utT4gNiEWmXuGYrA+8byVqIdf3MjQ3H/JE3SbJbLNjdKYINJBfIdIk6LcG/Trcw3TLZifBHdmerR7hzBsnITli3Bu7+II40j1oa1hsi8AmcIKiTIhvU4/7KXivT4zUrEMzyKwkrlzoNOSEqULk5Krbxz31iXzGrBCNdsoie+fyCaPrzcIsRN2iyumCIndz+c5jgOkFY5CXagopgaL7iBwpsvEpcn9lixwinvPJsTfca4VtgX5Gyw==,iv:DWRPtTvm5h9psBR6cLP06jOdtc7aN+rZ7LL6W9B2Z2g=,tag:hPJWqujIH5zPNybhQsPdfg==,type:str]
    config: ENC[AES256_GCM,data:xonbZznOhMQByxCLiDr8mKgEUSn1RiqUgztZ064ifuUFqEdRw8coM8ahpGDP8A5cDCke8dj5XjtBCQXctDwpASGKuosMoZFGfSnp1FWi/6LWZa5Zun4AA36nBO48beKHVHds49QymBZ1bNqPfuXD3DlwjsM6V15hrNtmyFzmjVXOjLW5CsSR1IpiFCNYD4kSK+q9GF0+oM+SHTXwXiZ27MwL67U5zKqDVOb1UB0MKA1e1bqrFkKBrLUOqOkJF/8OcAwMSUegdkavcz3SJAWR8P4IzIaGCIdGBUekzV5bxNtX5EIs9qhBimW4Yf3+vbSlq9Ya4bFnVgiug+ksMV6JV/QhET3GSKZ6cNLPV/qTk4/BMkQGTXrnhvfC417rbbzcKfcG95W8IIhwkgIdFEHOD3qK,iv:PXY/ptWoKuSt2afm2RXFpGPeVwpXY4ItoiJqxuW6vYQ=,tag:br0VvL142W//4GBTpwgSbg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiUW9CS3g0akpSbzNNbU5R
            SGo5dTN2YU13am1Ma2gzM0RtL01pY1ZROG44Cm5JRmtlSTNkYlBxWUo3UkQ1STdZ
            QlFNZFpydTJYREgydS9oNkFUOUozVHMKLS0tIFd0RzQ5SnozNUZpWXY4bmlPWWR4
            Ulg5cS9VNHNiYjNOTE9RTDJTYjJXWDQKHgSEHlhp4Nv7gBWmixLmj7jXqczl+43z
            wFBFdO1v/SCnPk7TiacAquXqqyelUPmiCtkWL2Co/tfAnZhbFqjIaA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1a73alcfdvadv96hc68nx6sf4wdzysnnnvy4l634hq569vx377chsrck77m
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-15T04:18:06Z"
    mac: ENC[AES256_GCM,data:wupi94o4dJ4m0b2cpTTj0etITX/0nUEl847MzSPQlov1rB71Ah+SKX2lO5HBF83njJTb7KonGzGWotRObaz1824O6GauHqtw5ZeYebJFUB9098dmK4wR+AfHWVS3Jou+Y4lUNxZUYYteDDjFosrmJwDm/nzvbMhXgG6Q/F7T9zY=,iv:o8gnUV7J3krlj09+Ozkyg00wu5AMIobORpC8rlGy/zo=,tag:RPK0581k2d4+XARI26/rfw==,type:str]
    version: 3.13.2
