apiVersion: v1
data:
    password: ENC[AES256_GCM,data:3/2acJ3/vFiMQ36rXI1JqjUSCdrZ1ijl+91K11vBYzuWM+N3Fk35hg8if7Xq/zrxSmig3nhYK3PrAQBUUitrKA+oWmrpENghSgjB9kYq1vjocqzXyAEO9Q==,iv:VcIkd5xcLjH77iDBTVgpZU7gAtzfcZGM2dmwAiKog9o=,tag:BXdSOJG1upQSCWXqn4+Qaw==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: gitlab-valkey
    namespace: gitlab
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4VUR2cm15SjNEc2doRThS
            aEZ2MzhHb0trdlJqcWRPRDNZL1llUHZUMVZZCldMS2VxdVNBcXlOUDFTR0hnK1l0
            SUZUcHdBQ2p2b0ZvRnhydGFnQnc2WUEKLS0tIDk4YmlYeGN4S1IyOWd0V3p0WGxH
            cnBnNGNxekxSVXJRTzdOQjEyNWxRamMKPuh21NcUketw1CbJ2zk7n9UXKr6f9ZHK
            tHf30VAk5ipuE8P92I2LFAR9ZXPwG13EK2OMZLadxVP3Tk8d7wPIVA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1a73alcfdvadv96hc68nx6sf4wdzysnnnvy4l634hq569vx377chsrck77m
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-15T03:38:25Z"
    mac: ENC[AES256_GCM,data:2rr8zlR/AVFScQjmakUeYJCZszX6HFuXbnvJXThCZgVOCqYUZ9GHVLGzt0futPbzkEg35eC5ULc8RABc0t2PSaDfOSlzXu0xTzZHgWxOCJCE4DjCazJWYV5zPj6eXt2a15lL650PTXmOrtvD0M578UYU0jdWnLcd0ZHMsDWj4Xw=,iv:52jt4AGCohy+nIHCLDI1Nvu/MaK2HD08TUwOJvGkrkg=,tag:GVUKAQv+8dc0pJ6iVFBEyA==,type:str]
    version: 3.13.2
