apiVersion: v1
data:
    values.yaml: ENC[AES256_GCM,data:NyTNvbBr9gPIQhwDD3WMEu7mDswoLFwo8ez7VRMYVMI5/daP/vH/mxAs2JZo2zxSWeDam5Rzu2SKkgbjttQpxycOU535GFGl+WxpyuCz5+cBxEsNXJ4XgCg/axQuNxZ3eingaQ==,iv:YqKA2ndjc86ivH/QEAIGAsd5CMF4+u4YkqYz8oCu2hM=,tag:04sRrncZSKnq0/UPU/S+Ig==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: gitlab-hosts
    namespace: gitlab
sops:
    age:
        - recipient: age1a73alcfdvadv96hc68nx6sf4wdzysnnnvy4l634hq569vx377chsrck77m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWVW1JMDhORnlIbXFsdEFV
            OUdvb3BqdmJzcHpkc0R6KzFWbmo3bGVqY1VnCm4yN0kvbW1meExNRVhxcE9nMGtI
            akwyMVY3WndJVFBJZHRrVjVkays5SVEKLS0tIDN2cm9aTUNJTWxyM3hCbEJVcUZJ
            YTJKd2lOTEZsZHRWYXZiVVRHNVgrdmcKzRAfjo3v0oxXc4LbQbUGG/muQ94L2RJh
            6Dp0QvK5RAVWLm2DIFa4v3/guOkau4zKSn7319miTI+M282McqsT8Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-17T00:44:10Z"
    mac: ENC[AES256_GCM,data:/I69c4HTUI8gBlCfSSuXbdIF6o0N1MdwpMniPUNO7Gm2HvI12U8t/5KeIkNyPwjZEhu8EbTzQhULeVyFNShoFtMg3OtywK5j59aZRZ3b5h1FQ3AUE51eYcpoWaUtfaA5uSEJUIm1YIG018PcUBJ5OobWX1PuuLOMlG1dXdkfdXo=,iv:IudSTl0H6SM8j9lf5Y4mHS0KziXN54SoWnV33sB6KPs=,tag:go63IdEYfzYBpGvq+j8CpQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
