apiVersion: v1
kind: Secret
metadata:
    name: gitlab-garage-rpc
    namespace: gitlab
stringData:
    rpcSecret: ENC[AES256_GCM,data:GjIl0AF2gHpMDF32OROnIeuA3cB7b4K8h4wieRYKVlctQoEfgnDx99mN/q0QMmwHyXHe1AHOh00xNSxGs/a9gw==,iv:cqI1Zmra7xj3fXMlObV0wGqOhqbMeERZC0plWs/Y1zo=,tag:x2qgZ1VeT6FHNS5Sn1IRrA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmamkxeEozYWZtVSsxRW9l
            RWlVSTI4NXQ0OHhFVkluSnRUVTBoOVVCVTBRCndZTXNMTDFUUm9YdDVoMXBHa1Jo
            ZVllWnhWY2dIejdQdktDUUNsVGdMam8KLS0tIHlKVFRHQW16ZjR6V1piY0VYcmln
            bllVaWVsZjA1QjVOenZvK2dpMFFDamsKwGcl7D/QmbYUfKFJ5Ew/ah9XFbiT36WX
            jpOyBSLATlJG13JZYS2s6COkbYN9jMs5kczgaP4JwXlFjdkXuUVLRg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1a73alcfdvadv96hc68nx6sf4wdzysnnnvy4l634hq569vx377chsrck77m
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-15T04:17:44Z"
    mac: ENC[AES256_GCM,data:yDsKn8LsZxZ/YtYD9rBesm0Iz7xshnAIz0h2nYIY4JQQ2/4jng1O7+1U7yLXUHV04iNT6SUE4hh9+EDhXotgxgZJ1pNbT/zASlaOlPmuNrxmEUFAQu3N4vZRtLEPRjHJ4Kdp835+aXrdKtOgoDZk7T8uyD1tuxK0iKi3A4TGOxg=,iv:eV5LoqDgMwr/xcOaUT5cq+6V9GK3/kYUYNFiXDsnlRs=,tag:xPDGTUFgw2Ne2RL51w3liQ==,type:str]
    version: 3.13.2
