apiVersion: v1
data:
    accessKey: ENC[AES256_GCM,data:Ew22rZykmF8cGnvQmPG6RkeN3jWV2bO81aO4618JUaPo48NsVAs2XdO8Q7xtMNCWLah7bNrox5KE/oNrjB3cPsl1fsxJduyPLEeMAB7siHq02MzXSDRDYw==,iv:FQH7miy4BB+Y34YnGTnTPp679ggTc4JWcMLH9cBHoGQ=,tag:e39i6bJyXN1MDg0z+X6Jfg==,type:str]
    config: ENC[AES256_GCM,data:/GUkQf8dGsM/sUazCq27yNf/bdHGH9gYY1S1ca2GaE1Sdtp+VGVXyDZAo88bXdHXhEb+wJp9zLZKRsFdI4GYD7cJICdQPWybVLpSLhgQGyHUiIxSc3EsGz2uLxnfepf4L240rJxV6Kp7lO27GaWtcgvHI8pN3Sm3bvXO+f0rvMNtKw1mvoTNd9YBvpz94kk0tl5vEDpC5KdCDFVfLJWCyTou6XD60WzBUCUA90MaCuQLVyOqutC3+eI7xcX/F8K2sQiyOnW50SP1/qGyS0rBnn2TtxFocNV5HO1M9QgbCizl3ZsaotYaKhgOxAgbR4elPZQ6XoM/9sTh7awz0/y6lVyqbYX2cc0+85fgbPg8uLUiCqG7AetriBVmLi5ulTZdmIQ93gCugviXnxsuATxGqV5KYAAn26xHAk6dVfZ7Csr0xH0SKNFGmNAVGYlPiTs6tIGoPtLiVU1eWqHwaQNabqTzkNjdRIUVn183kCYir4wgcxyve0EulZ99oCmi/keI5VBQcjQn8wJ0suvlRS1rwR6Gz545S/VKvkiRxGgiwJVl0QBxET88tT5kwIt8s5r/UPRQgkhTPUutf3TIPx4AeybTnxLqi/Jzxeb8lBQHfBTspzHPjLsQbHUcrkvv2Wz5VLwZTmmQCjMb1KChDSPmcA==,iv:hzk9QZ4X13x4r9qWPfoT5HuLB/YgdTmKahkhLHWAvEo=,tag:0WK8pMUGtvgEFlyKYJ2nXQ==,type:str]
    connection: ENC[AES256_GCM,data:oPIlDa+vPcegpdkC58cEw9GJRI0KkEBcrtUDSjeS261GhWaD+QEFz0oo3OLEuRW8Y5DryQ1bdT39014HLcNTLDbmcRp5Qqb2uTraJa3evAUaVILnMm1Myx64uXG2ReBIeZo7QAf2dyX61bAk2uo8SQSJTRMeaJm/9p+aK//jsaN8kjUasEYfNlrw/bq+zQUJfg2u1BBx+iWyzLwWIiVz5cbj6FHDFvGSFN9TObWZIJoJkL5emsHxDaqrYhb1F6uzSiD03E1ydFf2PTOZH85C2DO3UjbKgFI4YQtOtjyTuI8X9D6+TwY3oiLCp89EPqFpBf81QEVDov9hnU6iIftYUjdC5jxk7K/ZvvC3PvjWSr3Ei/c4gmnBLGzu+zKzmtZ66x2xf0OD0XpTZqPXVJ8ntv+vK5FTBhCZgVPvWjOOkk4wAsqiGL9fJ/NNl5GiCs2S9gNMPXbRCbMRIp9RWYqN+K0/mYJQg6MN0N0BaSV/QrE1deLscS/OQWCXWlLqZrE9VdGe3TcJVW0=,iv:A9oqFoDcPFkIPntX1xQb360sXVSO02IQOb4i/YWuiDA=,tag:J3JsgL6pJuOmeEFwc9Jmng==,type:str]
    secretKey: ENC[AES256_GCM,data:JDaTbGvBB0BiLERBMWwIvtKD/TbRAp8vJW7H9bHhhyUk3XjHKFAWsS38BBjtlV5SXkvGDtPX0ONK9R0ygybqnSeqxNJrN9AeLrCIc2+N4kDKcy34T/PY8g==,iv:ZDIfVm1Lb0mhG+4wBr0MLxEnsda56guAeG2elTQt0qo=,tag:o5MIeM6lTcrxZN8o0y7LPQ==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: gitlab-object-storage
    namespace: gitlab
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvSGlEU2dDc2NQSEhOUE5s
            WHUzSHM3VDc4SU5sMW5sL003SFRQTkhSM1hzCkdoc1lCNDV6ZCtVU2t3N2VleDkv
            NldPZDJySSt0S3NMN0M4aXpqKzlxTFUKLS0tIEhSS3ZCYW1zTEpqeFYvNUxvcVlI
            QU9aelE0elQzSE5NQ0xua21PNVlOUFEKbjulCTtmV5rNwur7nMMJADmDXrQqUPxB
            sWIf3CzNF/uxBup8fG3KeErq20v6vvjXvwolLPzNXSrKWaJbGpMG5w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1a73alcfdvadv96hc68nx6sf4wdzysnnnvy4l634hq569vx377chsrck77m
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-15T03:12:46Z"
    mac: ENC[AES256_GCM,data:W9bxuK0cTnnD1ZVzbk1Fn3t6AzvrNVhOSXyADOvHKbs3YyM0/+I+8UAokcdq5mWkNgs1thODC2Tphjmt2AaNK8X+5XAW2x/X3NxS5Pu863pN38GZiYy3N/u6MlbdYKk/yjMYW6ltnzOMLKeFU5QnQyyvDrE7idYcqc4v/phpG+I=,iv:UdSjcuUeoC5f300ueWub7qKgZ5bI1ya8GPOhTQR3dnk=,tag:zAjWN7HgyG7KdI3qp4DlDw==,type:str]
    version: 3.13.2
