apiVersion: v1
data:
    password: ENC[AES256_GCM,data:FbdJuq7mDb6pGsbBgV33pdyv70D0b2LTwbKpKXlJk6BkfTd/lB6koQYSPSQbW/hUUN6IV6ycFocv+DduZG6eRCW51YZ+McLGmhareYfnOgnwP5j9YMOwSA==,iv:ujuFAENtdDaD8aHAhj8tTHIqWmkhH9KpNAK20eK2PQI=,tag:CcjIqQ+gEffP9oKslnTuQw==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: gitlab-valkey
    namespace: gitlab
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNSElWSGFrNTlOZkVoamFO
            NzJaZk0wUitRNkk3MWkwTHJqRWs2a2UzK1dBClk2VGtIOU1HWjhScitFejRWdGtS
            N3Jhc2ZzSWM2WCt1bVhDazBXcnY0a2MKLS0tIHpiNUxQV0ZHWHBLSnhtY3hlaVdD
            bU5kK3F0YjdCWHppTkMySDROdmJiOVkK4r1KebfFDtFRuB0Ndkp3aNFCPjYCFVMo
            Trr0As1yM7hE/4ivwk5922MWheyWxj09a3+15GSWEco2Bh0LZ3Ow0A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1a73alcfdvadv96hc68nx6sf4wdzysnnnvy4l634hq569vx377chsrck77m
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-15T03:12:46Z"
    mac: ENC[AES256_GCM,data:tCyQwCH3LFvw1T+0ClgiMf4QMruthZOO6/+cwDl+NcPGLEb/QJJy9FwGB47i+q86mZyUclyGYo38OA8sfGmwHQHPgP1P9XxjhpGLxcr/W3D3V8fayrgswMqVb601PzoSq3akkrXKIxDis5Yb0WSdHBA2HvlSjwVc9lP6B6OL0+s=,iv:+TLR4p+gzg7auKx7MItb41oT84d4U4DKI2g8ovvEPQM=,tag:YEsn3ocI8VxsYsTBOAxLkA==,type:str]
    version: 3.13.2
