apiVersion: v1
data:
    password: ENC[AES256_GCM,data:JZS3gE/sUPn6nACMev3bUP1MXI/i4wrEetlzYdJdbBn4qQN3yE/mWwx9n7Y=,iv:XJhPHmunGyAeKLzbLcxXURfyVx4J24w1KM4fNNTTJvs=,tag:Qr3oUl3eJ3UdzDcI0DjlMg==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: gitlab-gitlab-initial-root-password
    namespace: gitlab
sops:
    age:
        - recipient: age1a73alcfdvadv96hc68nx6sf4wdzysnnnvy4l634hq569vx377chsrck77m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIRDA0ak5JSzBVSnlNYUE5
            bFRjODViZEJnMHZabkNIY0k5eEh2WWZOQndzClVyaUxJM3hJeVZScm1XaVhLUjVh
            RGFYdGFBSXh6eXBMSVcreEFNdW5DNmcKLS0tIFJ3RXpTNC96NVgxRVNBTXBsN0NZ
            eG1yU0M3enlTSGRPZ0xqaWd6TFMvNXMKFskyH2pjWQo7N7/soUhU8dPWS0M70jQK
            JmOQxpUXHBvBB+wxUWfAAfTRP9GiPFZSsi0WjEC2BHsSOL5AX6ETZA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-17T00:56:40Z"
    mac: ENC[AES256_GCM,data:FO7zaQEo5lzh6IzJ79Vx9p1/TQ2VvDSOZkR6ysaZ9UlZyl1WBBNF4qrMJSDb0MY1UI9GPDnw0OUoz7YN2bG6dipyzD6h7HoLH7bUpE0oLi8gGTQoHXTOn39CFSCKZuZ4E9JjNUS//JcqCc49FdhoCU3TxqMu8oNuGmJJ+US5SGs=,iv:YMxkEBsxi9mvGIIYjmaV5WQHCv4+cXjHFgV4HDgjgLE=,tag:uOSs0rGEv0gBzLtXTTRQXw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
