apiVersion: v1
data:
    database: ENC[AES256_GCM,data:5qwro4K/PjYdW+VkfJkVylIHNZOrs1baOQ8YlQ==,iv:Hc/0gfKQm887Q44stE+S5fs353LqQOjBOlv8SUDpEJg=,tag:k65rYmB5kUG1pudzAmaApQ==,type:str]
    host: ENC[AES256_GCM,data:zEx6R2EIxXmW/N9O0NN0Y1qg2fJVyhz0kYvsLFMIF/67g3x7l9DtN9rUZd/1pYld,iv:Kb+bjB7jFRzWxvZ2zXglg7LF+vVJ20IGFDrbG1L7KHg=,tag:ttLlfAoJ5AEmtHEaqCaZ3Q==,type:str]
    password: ENC[AES256_GCM,data:szKhxRQ2bzTf+Q7VExzXMrQtXEO/SY59k7hzkKIqQR4L2Wgz+arqxg==,iv:OLJLd29qttLMo6e8XitIJyqgg6Gu4LuNCEpjoarkz2U=,tag:oDMPnK5swy6k38V226f5fQ==,type:str]
    port: ENC[AES256_GCM,data:5ARReG5hqQY=,iv:6TKF29n4D9xH8N88/GG8egQtbo2a27MgcairFqM3jj0=,tag:7DxC9uAqAlCBmI9jdc4NJQ==,type:str]
    username: ENC[AES256_GCM,data:KpTF23b5GXQ=,iv:sYTmV+tGh9WZVleC8FcTns5iuXlfwfb1DLxuHIlTI9c=,tag:MydQUtYAjHyH7TOrjtT3xQ==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: gitlab-db
    namespace: gitlab
sops:
    age:
        - recipient: age1a73alcfdvadv96hc68nx6sf4wdzysnnnvy4l634hq569vx377chsrck77m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBZEVFZDE0U0dMWjNxTXQ1
            SzFGYUtpVndZMFpaRmhRQXU3bzVGNklkZlVFClp4dFBUenhtMlFJWHRvVkczRVM5
            akRjMGFUaFRITWpNblpFU0JUeWc1b1kKLS0tIDVtaE9ocG1tRWJKRE5QemhVRW9I
            aE1VUitXOFRZZC84bVRjaWo2SFlNc3MK4K1atP2DvAZjcrt+lZNTwVjFRSY7l8UT
            aeGpLmUO7t+JICb/VAzAmWF8Cegcv0QXFvnjwBLySk3/4/Hkr29x3A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-17T00:38:18Z"
    mac: ENC[AES256_GCM,data:0bbcZIzJi+3xw7+az0kLUQUk/ueR4MLAFMvx8JMsLZrt5YkX95+7eT9YbLLK5NEzc0Yf8FM37I5XpORtXAyGjLYlPh0ySWpCLm5J+x3lOWKlMSLLoOWZAJG1RDjlOdb+k//BlNgte4s81CwGDhCRqZgXeJiQMAuI9FfbmzKHKf8=,iv:KFE8BTPEf4TIP3WNwgsHXemJCB2sL6DfRAZTSZ9PQAY=,tag:MriTF7r7mP3Auw0mS/THBA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
