apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gitlab
  namespace: gitlab
spec:
  interval: 30m
  timeout: 20m
  chart:
    spec:
      chart: gitlab
      version: 9.11.2
      sourceRef:
        kind: HelmRepository
        name: gitlab
        namespace: flux-system
  install:
    createNamespace: false
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  valuesFrom:
    - kind: Secret
      name: gitlab-hosts
      valuesKey: values.yaml
    - kind: Secret
      name: gitlab-db
      valuesKey: host
      targetPath: global.psql.host
    - kind: Secret
      name: gitlab-db
      valuesKey: port
      targetPath: global.psql.port
    - kind: Secret
      name: gitlab-db
      valuesKey: database
      targetPath: global.psql.database
    - kind: Secret
      name: gitlab-db
      valuesKey: username
      targetPath: global.psql.username
  values:
    installCertmanager: false
    nginx-ingress:
      enabled: false
    prometheus:
      install: false
    postgresql:
      install: false
    gitlab-runner:
      install: false
    traefik:
      install: false
    global:
      ingress:
        class: traefik
        provider: traefik
        configureCertmanager: false
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production-dns01-cloudflare
        tls:
          enabled: true
          secretName: gitlab-web-tls
      time_zone: Europe/London
      initialRootPassword:
        secret: gitlab-gitlab-initial-root-password
        key: password
      psql:
        password:
          secret: gitlab-db
          key: password
      minio:
        enabled: true
      registry:
        enabled: false
      kas:
        enabled: false
    registry:
      enabled: false
      ingress:
        enabled: false
    minio:
      ingress:
        enabled: false
      persistence:
        storageClass: "-"
        size: 20Gi
        volumeName: gitlab-minio-data
    redis:
      master:
        persistence:
          existingClaim: gitlab-redis-data
    gitlab:
      gitaly:
        persistence:
          storageClass: "-"
          size: 100Gi
          matchLabels:
            gitlab-storage: gitaly-default
      kas:
        enabled: false
        ingress:
          enabled: false
      webservice:
        minReplicas: 1
        maxReplicas: 1
      sidekiq:
        minReplicas: 1
        maxReplicas: 1
      gitlab-shell:
        minReplicas: 1
        maxReplicas: 1
        service:
          type: NodePort
          nodePort: 30022
