apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - helmrepository.yaml
  - persistentvolume-gitaly.yaml
  - persistentvolume-redis.yaml
  - persistentvolumeclaim-redis.yaml
  - persistentvolume-valkey.yaml
  - persistentvolumeclaim-valkey.yaml
  - garage-storage.yaml
  - gitlab-db.secret.sops.yaml
  - gitlab-hosts.secret.sops.yaml
  - gitlab-initial-root-password.secret.sops.yaml
  - gitlab-valkey.secret.sops.yaml
  - gitlab-garage-rpc.secret.sops.yaml
  - gitlab-garage.secret.sops.yaml
  - valkey.yaml
  - garage.yaml
  - helmrelease.yaml
