apiVersion: v1
kind: Service
metadata:
  name: gitlab-object-storage
  namespace: gitlab
spec:
  selector:
    app.kubernetes.io/name: gitlab-object-storage
  ports:
    - name: http
      port: 9000
      targetPort: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitlab-object-storage
  namespace: gitlab
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: gitlab-object-storage
  template:
    metadata:
      labels:
        app.kubernetes.io/name: gitlab-object-storage
    spec:
      automountServiceAccountToken: false
      securityContext:
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
        runAsNonRoot: true
        runAsUser: 1000
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: minio
          image: registry.gitlab.com/gitlab-org/cloud-native/mirror/images/minio/minio:RELEASE.2017-12-28T01-21-00Z
          imagePullPolicy: IfNotPresent
          args:
            - -C
            - /tmp/.minio
            - --quiet
            - server
            - /export
          env:
            - name: MINIO_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: gitlab-object-storage
                  key: accessKey
            - name: MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: gitlab-object-storage
                  key: secretKey
          ports:
            - name: http
              containerPort: 9000
          readinessProbe:
            tcpSocket:
              port: http
            periodSeconds: 5
          livenessProbe:
            tcpSocket:
              port: http
            periodSeconds: 10
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            runAsNonRoot: true
            runAsUser: 1000
          volumeMounts:
            - name: data
              mountPath: /export
            - name: config
              mountPath: /tmp/.minio
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: gitlab-minio
        - name: config
          emptyDir:
            medium: Memory
