apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitlab-redis-data
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  hostPath:
    path: /mnt/userdata-clusterfiles/k3s-volumes/gitlab-redis
    type: DirectoryOrCreate
  claimRef:
    namespace: gitlab
    name: gitlab-redis-data
