apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitlab-minio-data
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  hostPath:
    path: /mnt/erithc-clusterfiles/k3s-volumes/gitlab-minio
    type: DirectoryOrCreate
