apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitlab-gitaly-default
  labels:
    gitlab-storage: gitaly-default
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  hostPath:
    path: /mnt/userdata-clusterfiles/k3s-volumes/storage-code/gitlab
    type: DirectoryOrCreate
