apiVersion: v1
kind: PersistentVolume
metadata:
  name: observability-grafana-data
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  hostPath:
    path: /mnt/erithc-clusterfiles/k3s-volumes/observability-grafana
    type: DirectoryOrCreate
  claimRef:
    namespace: observability
    name: grafana-data
