apiVersion: v1
data:
    GF_DATABASE_HOST: ENC[AES256_GCM,data:zEN3DSvl9jvEZV6JVSjTUxeqILqhJYiLBWtgM9skKW6wi8GxFJHFVPOQnrPK7wWQUPI65mrppbQ=,iv:YNRyRG/Qm48OI9+J0wwV7K+WLrATDxSsCyGPY1EX/Kg=,tag:G2F7WLAJKG5r5UAdEIgCRQ==,type:str]
    GF_DATABASE_NAME: ENC[AES256_GCM,data:DmMuhhIH3nBRT5MI,iv:5FrXDeCNgYPrS9XmeSBByEQI1NyvyQJEKo3038hLAPI=,tag:PfCIh4aJuO+yq7xOuxL84w==,type:str]
    GF_DATABASE_PASSWORD: ENC[AES256_GCM,data:0HQBWo1WJSJRZcFEe3Ps4rTAktM22okHPlJ/CiODzknScjjgy6Bt+4al5TI7yEKpMrniymgaPhceMalpAboOnQ==,iv:Ol23Fz5Zi7exVcefQ1LAkX1mNhJBckc4IvjibapEyGc=,tag:Xmnt5jR9KJqufLHrSB4H/Q==,type:str]
    GF_DATABASE_SSL_MODE: ENC[AES256_GCM,data:5DmKgkqTTept+s4d,iv:D7rhqIn9n/e5PVh5gkn66jNRuz2FlTkDv9BYecaSyX4=,tag:Hl6uP8FJENL+qdLH83rTxA==,type:str]
    GF_DATABASE_TYPE: ENC[AES256_GCM,data:zPsqtSNw2E0HpKuT,iv:sDVJv4Yze12jgglolzJk5Oq4jc+FcC6c14MSaXu4Zek=,tag:77c3KmiAEZBrI29a9YuCgA==,type:str]
    GF_DATABASE_USER: ENC[AES256_GCM,data:rHtSwgv3T/PokyrV,iv:Qvam6RzqO2/w71fQkRG+0FDgpIUyvzJZZHfW1DmulXQ=,tag:gcfAGJDA/6U1MvX5EbmP2Q==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: grafana-postgres-auth
    namespace: observability
sops:
    age:
        - recipient: age1a73alcfdvadv96hc68nx6sf4wdzysnnnvy4l634hq569vx377chsrck77m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0eGZWRnI4akUzOXRPeEZy
            WDRzbGtIMjNmTjUvRXFQOXFWL3J3VWQyWkNVCmNWcllleVlRMjZUandkOFdFQjZa
            ZmRpRGxBTFROQ1lQQytGRSt0QWR5YzQKLS0tIEo3UTBTdEZ6S21JZFlCcmVEMDVq
            M3dCT0FYN2MvUWh3cTRWeDB5Skt5M0EK3W+j0JaxvdTpNqP1psjLIYlAJ7ekCXYZ
            6wA7eY8/jkW0/ikMOkyzgdDk9xbRItBanZKgHLp7ce9lRtAj4RVEkA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-19T02:41:12Z"
    mac: ENC[AES256_GCM,data:Q4PnayGepLBWWlIn8D9SGa3CUDJOJj13yMmjryzIhX+6Um5ejsKLGpVrfXLKm4BPoNtLMeON6zNw2bslK1S/ZEBYGnB+6y9mWewHLmvql/4WvscpDd59/pxup8AI/w9kJK9bFQQ64RWrHeWiwUZJALXXO07LFVu83SVr/femzHw=,iv:bGTARJmlH1dPzkDbc6LjZPsaWaeWBEsmcKvXGLrk1/g=,tag:6ocYBCLnpsOY1aeGn6Jt2A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
