apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - helmrepository.yaml
  - helmrepository-grafana-community.yaml
  - grafana-persistentvolume.yaml
  - grafana-persistentvolumeclaim.yaml
  - grafana-postgres-auth.secret.sops.yaml
  - loki-persistentvolume.yaml
  - loki-helmrelease.yaml
  - grafana-helmrelease.yaml
  - promtail-helmrelease.yaml
