apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki
  namespace: observability
spec:
  interval: 30m
  chart:
    spec:
      chart: loki
      version: 6.55.0
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  install:
    createNamespace: false
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    fullnameOverride: loki
    deploymentMode: SingleBinary
    gateway:
      enabled: false
    lokiCanary:
      enabled: false
    test:
      enabled: false
    memcached:
      enabled: false
    chunksCache:
      enabled: false
    resultsCache:
      enabled: false
    minio:
      enabled: false
    ruler:
      enabled: false
    loki:
      auth_enabled: false
      commonConfig:
        replication_factor: 1
      schemaConfig:
        configs:
          - from: "2024-04-01"
            store: tsdb
            object_store: filesystem
            schema: v13
            index:
              prefix: loki_index_
              period: 24h
      storage:
        type: filesystem
      limits_config:
        allow_structured_metadata: true
        max_query_lookback: 168h
        retention_period: 168h
        volume_enabled: true
      compactor:
        compaction_interval: 10m
        delete_request_store: filesystem
        retention_delete_delay: 2h
        retention_enabled: true
        working_directory: /var/loki/retention
    singleBinary:
      replicas: 1
      persistence:
        enabled: true
        storageClass: "-"
        size: 20Gi
        selector:
          matchLabels:
            observability-volume: loki
        enableStatefulSetAutoDeletePVC: false
        whenDeleted: Retain
        whenScaled: Retain
    backend:
      replicas: 0
    read:
      replicas: 0
    write:
      replicas: 0
    ingester:
      replicas: 0
    querier:
      replicas: 0
    queryFrontend:
      replicas: 0
    queryScheduler:
      replicas: 0
    distributor:
      replicas: 0
    compactor:
      replicas: 0
    indexGateway:
      replicas: 0
    bloomCompactor:
      replicas: 0
    bloomGateway:
      replicas: 0
