apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: promtail
  namespace: observability
spec:
  interval: 30m
  dependsOn:
    - name: loki
      namespace: observability
  chart:
    spec:
      chart: promtail
      version: 6.17.1
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  install:
    createNamespace: false
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    config:
      clients:
        - url: http://loki:3100/loki/api/v1/push
    tolerations:
      - operator: Exists
