apiVersion: v1
data:
    api-token: ENC[AES256_GCM,data:CFA9G8c6SDmauCjumKoezNEO9O4rCZXeYO7p7aTOS2xFa2C5Nh92QTgzQwmobPPzBTaF9Gz7lDk=,iv:Wz0Gm4aWOXzBHDCbnAQ9qT811gIn+4lsAApEJy/gR7M=,tag:xtwz55OfFKYuqZwKF+yU9A==,type:str]
kind: Secret
metadata:
    name: cloudflare-api-token
    namespace: cert-manager
sops:
    age:
        - recipient: age1a73alcfdvadv96hc68nx6sf4wdzysnnnvy4l634hq569vx377chsrck77m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqcmtWWDlQZTJhZzEvNTJY
            RXNlRS81VVBZLzFxblFFMHllRW5NUUJ3MHpJCndEekovTkdnekNUME4wRXl4Z2RH
            ZGkrb1FDYWRvbDg5UUZFWGNrUWNUMEUKLS0tIG1aSE5iRXd2amxzdTNuMkMydUoz
            ZzdxOUFnVDhRZlRBUXFSdDZneVFneEkKgsH3adlWqCIVDTQsF752m+N9X4IluXKY
            +hPFcYqZT0bnVPCND/yXNpRUqGkk26Zv/4BM//QCeAGiOH1E2UVRmw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-11T02:54:11Z"
    mac: ENC[AES256_GCM,data:f5KUtA+NqMQjZWZieVBlwkUOxxS9JzN7BITTiluOgTv1j8Z24nHQO7yO8VfsXe1wdUyihGh6G2l9Yj44tSi56KYv76OtrTsDxYDjXsKvFitDkcQD8QbrfYFdmMKtbtiHv1Bfce8IXIVL/jcsLiaWHc7qLUIUGKBg/V506CFit3U=,iv:h7grk5EhJM5V5VMYyA3ZdLA8mRoJ32sZnN2+pE46M58=,tag:xHkbZebirRRU2Jxjd/EvtA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
