apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - persistentvolume.yaml
  - persistentvolumeclaim.yaml
  - postgres-auth.secret.sops.yaml
  - postgres-tls.secret.sops.yaml
  - deployment.yaml
  - service.yaml
