apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-data
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  hostPath:
    path: /mnt/erithc-clusterfiles/k3s-volumes/postgres
    type: DirectoryOrCreate
  claimRef:
    namespace: postgres
    name: postgres-data
