apiVersion: v1
data:
    postgres-database: ENC[AES256_GCM,data:SWS+/F394lt/eTmD,iv:kZ9sEBDt9fDYRjtegMebPz29wQxs2Z8EIxSDiG0Cecs=,tag:0TLnzV9keHIdQCqoj5Z18g==,type:str]
    postgres-password: ENC[AES256_GCM,data:7tcnpcX+dNkffNrQlwstj2SXRz+8FG9J27Qj4Lmb370Q99w0W3SrTYrYi2o=,iv:kyJDWXy3m23O5bfWV471DoHbeYGdCCzuUhQlDAWDD8c=,tag:l4zLQMPRtDjpP+1U1jOBbQ==,type:str]
    postgres-user: ENC[AES256_GCM,data:fIDhK/I1qi6ElTu1,iv:VshLQoujZx+hJQwbiZ+fzcsWOMKjQOJrYDp5G8RYt5Q=,tag:UeKJguq9vLxl18iYofZkOw==,type:str]
kind: Secret
metadata:
    name: postgres-auth
    namespace: postgres
sops:
    age:
        - recipient: age1a73alcfdvadv96hc68nx6sf4wdzysnnnvy4l634hq569vx377chsrck77m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCYThtY0NaNXRWa3VXMUxC
            VnJDWjhuKzRqNnZoN0NuRkZnY21RMlg3ZnhRClRzM1Jjb3Q5UlY5RTVXNjhnZWNB
            Z2FvUXVLcWwwVWdpY0NPdVVGUFYrOHMKLS0tIG5GQkIxdjJvdFJwM0hmb1BEWCtR
            ekppakhuY2lrZUFvOUdYRDdoVDBLZTQKIKBOFJl2dK4+C+r9QQIdePfrjdTjngma
            Ow3sTw0QZJatP9n11CpJq0fS7tSqD+v9PNmtvhw+Ao0kWiyxq8hgmA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-16T04:48:43Z"
    mac: ENC[AES256_GCM,data:uFwTBZnmhNWTceJeixGT+88mUarMgIwM1b6Y5s8pIbd7GaGJkws/kgaGux8mjUlxVkKi+8sXbNPUA2ANegBBtyzeqEZLazemtlrANNo8Ohsjr6SE5bBqq5k0KbPEGmpoDXrQb4KOaFaaOe/DjqAvdatA49IRIlX8zXs8sBZ8qi4=,iv:XWYlI+J5SkyU6tK0ktuxTJmX0BUwArWTBSnMcOl1jnM=,tag:fPxVoD3FM/OTz50r4XWcAQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
