apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres18-data
  namespace: postgres
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: ""
  volumeName: postgres18-data
